description: >
  Using Google's Dart Docker for testing
docker:
  - image: 'google/dart:<<parameters.tag>>'

working_directory: ~/repo
parameters:
  tag:
    default: "2.10.0"
    description: >
      Pick a specific google/dart image variant:
      https://hub.docker.com/r/google/dart/
    type: string
